# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  
  publishable_key: pk_test_JRUtAMC3yD4rrzFnZnYrldyF
  secret_key: sk_test_yUBlXRORy3RmMQKhghVL4x09

development:
  secret_key_base: 0a9b5e07fc4f47a992727cd3dc6e7201a93ad021a7ee65a870d941611b6bb74eef3d8e5edcd1a12738cf16e62b7e8e72ebb5b66df94b133230819dabe4fe23b6

test:
  secret_key_base: 7bd29bcc99fd5735d82a24dfd3c354b3001389335b0f61b47c71aaf2ca30f27b268331d4d9f6cbc324bd02e987b9cb802ed6bf6b35ce8d10d7e6c6a74b500c5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


